### health
GET http://localhost:8787/health

### get bangumi subject
GET http://localhost:8787/bangumi/subject/528438

### post bangumi subject
POST http://localhost:8787/bangumi/subject/528438
Authorization: Bearer 123456
