name: Fetch

on:
  schedule:
    - cron: '11 11 * * *'

  workflow_dispatch:
    inputs:
      overwrite:
        description: 'Overwrite the old data'
        type: boolean
        default: false
        required: true
      bangumi:
        description: 'Fetch Bangumi data'
        type: boolean
        default: true
        required: true
      tmdb:
        description: 'Fetch TMDB data'
        type: boolean
        default: true
        required: true

jobs:
  prepare:
    name: Prepare branch

    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch.outputs.branch }}
      overwrite: ${{ inputs.overwrite || 'false' }}

    permissions:
      contents: write

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v4

      - name: Prepare branch
        id: branch
        run: |
          BRANCH=fetch-data/$(date +"%Y-%m-%d")

          git checkout -B $BRANCH
          git push -u -f origin $BRANCH

          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

  bangumi:
    name: Fetch Bangumi

    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs:
      - prepare

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Fetch Bangumi
        if: ${{ inputs.bangumi }}
        run: |
          pnpm run bgmx fetch bangumi --overwrite=${{ needs.prepare.outputs.overwrite }} | tee run.log
          grep "^Info:"  run.log > bangumi-info.log  || true
          grep "^Error:" run.log > bangumi-error.log || true

          # Generate markdown summary
          output=data/bangumi.md
          echo '# Bangumi' > $output

          # Output Info
          echo '## Fetch new bangumi' >> $output
          info_diff=$(diff --new-line-format="%L" --old-line-format="" --unchanged-line-format="" "data/bangumi-info.log" "bangumi-info.log")
          echo "$info_diff" | while IFS= read -r line; do
            line="${line/Info: /}"
            line="${line/fetch /}"
            echo "- ${line}" >> $output
          done

          # Output Error
          echo '## Error' >> $output
          error_diff=$(diff --new-line-format="%L" --old-line-format="" --unchanged-line-format="" "data/bangumi-error.log" "bangumi-error.log")
          echo "$error_diff" | while IFS= read -r line; do
            line="${line/Error: /}"
            echo "- ${line}" >> $output
          done

          # Update
          grep "^Info:"  run.log > data/bangumi-info.log  || true
          grep "^Error:" run.log > data/bangumi-error.log || true

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: bangumi-data
      #     path: |
      #       data/bangumi/
      #       data/bangumi-*.log

      - name: Push changes
        if: ${{ inputs.bangumi }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %T")
          BRANCH=${{ needs.prepare.outputs.branch }}

          if [[ -n $(git status -s) ]]; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

            git add data
            git commit -m "feat(bgmd): update bangumi data at $TIMESTAMP"
            git push origin $BRANCH
          fi

  tmdb:
    name: Fetch TMDB

    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs:
      - prepare
      - bangumi

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Fetch TMDB
        if: ${{ inputs.tmdb }}
        run: |
          pnpm run bgmx fetch tmdb --overwrite=${{ needs.prepare.outputs.overwrite }} | tee run.log
          grep "^Info:"  run.log >  tmdb-info.log  || true
          grep "^Error:" run.log >  tmdb-error.log || true

          # Generate markdown summary
          output=data/tmdb.md
          echo '# tmdb' > $output

          # Output Info
          echo '## Fetch new bangumi' >> $output
          info_diff=$(diff --new-line-format="%L" --old-line-format="" --unchanged-line-format="" "data/tmdb-info.log" "tmdb-info.log")
          echo "$info_diff" | while IFS= read -r line; do
            line="${line/Info: /}"
            line="${line/fetch /}"
            echo "- ${line}" >> $output
          done

          # Output Error
          echo '## Error' >> $output
          error_diff=$(diff --new-line-format="%L" --old-line-format="" --unchanged-line-format="" "data/tmdb-error.log" "tmdb-error.log")
          echo "$error_diff" | while IFS= read -r line; do
            line="${line/Error: /}"
            echo "- ${line}" >> $output
          done

          # Update
          if [ "${{ needs.prepare.outputs.overwrite }}" = true ] ; then
            grep "^Info:"  run.log >  data/tmdb-info.log  || true
            grep "^Error:" run.log >  data/tmdb-error.log || true
          else
            grep "^Info:"  run.log >> data/tmdb-info.log  || true
            grep "^Error:" run.log >  data/tmdb-error.log || true
          fi

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: tmdb-data
      #     path: |
      #       data/tmdb/
      #       data/tmdb-*.log

      - name: Push changes
        if: ${{ inputs.tmdb }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %T")
          BRANCH=${{ needs.prepare.outputs.branch }}

          if [[ -n $(git status -s) ]]; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

            git add data
            git commit -m "feat(bgmd): update TMDB data at $TIMESTAMP"
            git push origin $BRANCH
          fi

  pr:
    name: Create Pull Request

    runs-on: ubuntu-latest

    needs:
      - prepare
      - bangumi
      - tmdb

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.branch }}
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%Y-%m-%d")

          pr_list=$(gh pr list --label=data)
          if [[ -n "$pr_list" ]]; then
            echo "$pr_list" | awk '{print $1}' | xargs gh pr close -d
          fi

          pr_body=$(cat data/bangumi.md data/tmdb.md || 'Update data')

          if [[ $(git rev-list --count origin/main..origin/${{ needs.prepare.outputs.branch }}) -gt 0 ]]; then
            gh pr create \
              --title "feat(bgmd): update data at $DATE" \
              --body  "$pr_body" \
              --head  "${{ needs.prepare.outputs.branch }}" \
              --label "data"
          fi
