name: Fetch

on:
  workflow_dispatch:
    inputs:
      overwrite:
        description: 'Overwrite the old data'
        type: boolean
        default: false
        required: true

jobs:
  prepare:
    name: Prepare branch

    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch.outputs.branch }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare branch
        id: branch
        run: |
          BRANCH=fetch-data/$(date +"%Y-%m-%d")

          git checkout -b $BRANCH
          git push -u -f origin $BRANCH

          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

  bangumi:
    name: Fetch Bangumi

    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs:
      - prepare

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Fetch Bangumi
        run: |
          npx tsx packages/bgmd/scripts/bangumi.ts --overwrite=${{ inputs.overwrite }} | tee run.log
          grep "^Error:" run.log > data/bangumi-error.log

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bangumi-data
          path: |
            data/bangumi/
            data/bangumi-*.log

      - name: Push changes
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %T")
          BRANCH=${{ needs.prepare.outputs.branch }}

          git checkout -b $BRANCH

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add data
          git commit -m "feat(bgmd): update bangumi data at $TIMESTAMP"
          git push origin $BRANCH

  tmdb:
    name: Fetch TMDB

    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs:
      - prepare
      - bangumi

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Fetch TMDB
        run: |
          npx tsx packages/bgmd/scripts/tmdb.ts --overwrite=${{ inputs.overwrite }} | tee run.log
          grep "^Info:"  run.log > data/tmdb-info.log
          grep "^Error:" run.log > data/tmdb-error.log

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tmdb-data
          path: |
            data/tmdb/
            data/tmdb-*.log

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %T")
          BRANCH=${{ needs.prepare.outputs.branch }}

          git checkout -b $BRANCH

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add data
          git commit -m "feat(bgmd): update TMDB data at $TIMESTAMP"
          git push origin $BRANCH

  pr:
    name: Create Pull Request

    runs-on: ubuntu-latest

    needs:
      - prepare
      - bangumi
      - tmdb

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.branch }}

      - name: Create Pull Request
        run: |
          DATE=$(date +"%Y-%m-%d")

          gh pr create \
            --title "feat(bgmd): update data at $DATE" \
            --body  "Update data" \
            --head  "${{ needs.prepare.outputs.branch }}" \
            --label "data"
