name: Fetch

on:
  workflow_dispatch:

jobs:
  tmdb:
    name: Fetch TMDB

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Fetch TMDB
        run: |
          npx tsx packages/bgmd/scripts/tmdb.ts --overwrite | tee run.log
          grep "^Info:"  run.log > data/tmdb-info.log
          grep "^Error:" run.log > data/tmdb-error.log

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: |
            data/tmdb/
            data/tmdb-*.log

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=fetch-tmdb/$(date +"%Y-%m-%d")

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git checkout -b $BRANCH
          git add data
          git commit -m "feat(bgmd): update TMDB data"
          git push --force --set-upstream origin $BRANCH

          gh pr create \
            --title "feat(bgmd): update TMDB data" \
            --body  "$(cat run.log)" \
            --head  "$BRANCH"
